version: '3.7'
services:
  eventstore.db:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
    # volumes:
    #   - type: volume
    #     source: eventstore-volume-data
    #     target: /c/data/eventstore/data
    #   - type: volume
    #     source: eventstore-volume-logs
    #     target: /c/data/eventstore/logs

  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: awat
    volumes:
      - mongodb_data:/data/db

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongodb_data:
    driver: local
